#!/usr/bin/env python3
"""
Extract CESR test vectors from KERIpy reference implementation.

Usage:
    python extract-from-keripy.py > keripy-vectors.json

Requires: pip install keri

Uses the same deterministic seeding as the Racket oracle:
raw bytes = repeat ASCII of first code char to fill raw-size.

If keripy is not installed, the vectors in keripy-vectors.json were
generated by this script and committed for offline cross-checking.
"""

import json
import sys

try:
    from keri.core.coring import Matter, MtrDex
    HAS_KERIPY = True
except ImportError:
    HAS_KERIPY = False
    print("keripy not installed. Install with: pip install keri", file=sys.stderr)
    print("Using pre-committed vectors instead.", file=sys.stderr)
    sys.exit(1)


# Representative codes for cross-checking
# (code, description, raw_size)
CODES = [
    ("A", "Ed25519 indexed sig both same", 64),
    ("B", "Ed25519 indexed sig current only", 64),
    ("D", "Ed25519 verification key", 32),
    ("E", "Blake3-256 digest", 32),
    ("0B", "Ed25519 signature", 64),
]


def deterministic_raw(code: str, raw_size: int) -> bytes:
    """Same seeding as Racket: fill with ASCII of first code char."""
    fill_byte = ord(code[0])
    return bytes([fill_byte] * raw_size)


def main():
    vectors = []
    for code, desc, rs in CODES:
        raw = deterministic_raw(code, rs)
        # Use Matter to encode via T<-R
        m = Matter(raw=raw, code=code)
        text = m.qb64  # text representation
        binary = m.qb2  # binary representation

        vectors.append({
            "code": code,
            "description": desc,
            "rawHex": raw.hex(),
            "rawSize": rs,
            "text": text,
            "binaryHex": binary.hex(),
            "textLength": len(text),
            "binaryLength": len(binary),
        })

    print(json.dumps(vectors, indent=2))


if __name__ == "__main__":
    main()
