#lang racket/base

;; Emit TypeScript CESR codec library from spec oracle data.
;; Produces cesr-codec.ts (exported library) and cesr-codec.test.ts (companion tests).
;; Usage: racket emit-library.rkt <output-dir>

(require racket/file
         "../cesr/tables.rkt"
         "../cesr/counters.rkt")

;; --- Helpers ---

(define (js-string s)
  (format "'~a'" s))

;; ============================================================
;; cesr-codec.ts emission
;; ============================================================

(define (emit-header port)
  (fprintf port "// Auto-generated by CESR spec oracle — do not edit\n\n"))

;; --- Types ---

(define (emit-types port)
  (fprintf port "// --- Types ---\n\n")
  (fprintf port "export interface CodeEntry {\n")
  (fprintf port "  readonly code: string;\n")
  (fprintf port "  readonly description: string;\n")
  (fprintf port "  readonly rawSize: number;\n")
  (fprintf port "  readonly category: string;\n")
  (fprintf port "}\n\n")
  (fprintf port "export interface CounterEntry {\n")
  (fprintf port "  readonly code: string;\n")
  (fprintf port "  readonly description: string;\n")
  (fprintf port "  readonly countRange: number;\n")
  (fprintf port "  readonly category: string;\n")
  (fprintf port "}\n\n")
  (fprintf port "export interface ParseResult {\n")
  (fprintf port "  readonly code: string;\n")
  (fprintf port "  readonly raw: Uint8Array;\n")
  (fprintf port "}\n\n"))

;; --- Tables ---

(define (emit-tables port)
  (fprintf port "// --- Tables ---\n\n")
  ;; CODE_TABLE
  (fprintf port "export const CODE_TABLE: readonly CodeEntry[] = [\n")
  (for ([entry (all-entries)])
    (fprintf port "  { code: ~a, description: ~a, rawSize: ~a, category: ~a },\n"
             (js-string (entry-code entry))
             (js-string (entry-description entry))
             (entry-raw-size entry)
             (js-string (entry-category entry))))
  (fprintf port "];\n\n")
  ;; COUNTER_TABLE
  (fprintf port "export const COUNTER_TABLE: readonly CounterEntry[] = [\n")
  (for ([entry (all-counter-entries)])
    (fprintf port "  { code: ~a, description: ~a, countRange: ~a, category: ~a },\n"
             (js-string (counter-entry-code entry))
             (js-string (counter-entry-description entry))
             (counter-entry-count-range entry)
             (js-string (counter-entry-category entry))))
  (fprintf port "];\n\n"))

;; --- Lookup Map ---

(define (emit-lookup-map port)
  (fprintf port "// --- Lookup ---\n\n")
  (fprintf port "export const CODE_LOOKUP: ReadonlyMap<string, CodeEntry> = new Map<string, CodeEntry>(\n")
  (fprintf port "  CODE_TABLE.map(e => [e.code, e] as const)\n")
  (fprintf port ");\n\n"))

;; --- Sizing Functions ---

(define (emit-sizing-fns port)
  (fprintf port "// --- Sizing ---\n\n")
  ;; padSize
  (fprintf port "export function padSize(_code: string, rawSize: number): number {\n")
  (fprintf port "  const r = rawSize % 3;\n")
  (fprintf port "  return r === 0 ? 0 : 3 - r;\n")
  (fprintf port "}\n\n")
  ;; textSize
  (fprintf port "export function textSize(code: string, rawSize: number): number {\n")
  (fprintf port "  const ps = padSize(code, rawSize);\n")
  (fprintf port "  return ((ps + rawSize) / 3) * 4;\n")
  (fprintf port "}\n\n")
  ;; binarySize
  (fprintf port "export function binarySize(code: string, rawSize: number): number {\n")
  (fprintf port "  return padSize(code, rawSize) + rawSize;\n")
  (fprintf port "}\n\n")
  ;; counterTextSize
  (fprintf port "export function counterTextSize(code: string): number {\n")
  (fprintf port "  return 2 * code.length;\n")
  (fprintf port "}\n\n")
  ;; counterBinarySize
  (fprintf port "export function counterBinarySize(code: string): number {\n")
  (fprintf port "  return (3 * counterTextSize(code)) / 4;\n")
  (fprintf port "}\n\n"))

;; --- Selector Dispatch ---

(define (emit-selector-dispatch port)
  (fprintf port "export function selectorDispatch(firstChar: string): 1 | 2 {\n")
  (fprintf port "  return (firstChar === '0' || firstChar === '-') ? 2 : 1;\n")
  (fprintf port "}\n\n"))

;; --- Lead Constrained Bits ---

(define (emit-lead-constrained-bits port)
  (fprintf port "export function leadConstrainedBits(code: string, rawSize: number): number {\n")
  (fprintf port "  const cs = code.length;\n")
  (fprintf port "  const ps = padSize(code, rawSize);\n")
  (fprintf port "  return cs > ps ? (cs - ps) * 6 : 0;\n")
  (fprintf port "}\n\n"))

;; --- Base64url Codec ---

(define (emit-base64url port)
  (fprintf port "// --- Base64url codec ---\n\n")
  (fprintf port "const B64URL = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';\n\n")
  ;; encode
  (fprintf port "export function base64urlEncode(bytes: Uint8Array): string {\n")
  (fprintf port "  let result = '';\n")
  (fprintf port "  for (let i = 0; i < bytes.length; i += 3) {\n")
  (fprintf port "    const b0 = bytes[i];\n")
  (fprintf port "    const b1 = i + 1 < bytes.length ? bytes[i + 1] : 0;\n")
  (fprintf port "    const b2 = i + 2 < bytes.length ? bytes[i + 2] : 0;\n")
  (fprintf port "    const n = (b0 << 16) | (b1 << 8) | b2;\n")
  (fprintf port "    const remaining = bytes.length - i;\n")
  (fprintf port "    result += B64URL[(n >> 18) & 63];\n")
  (fprintf port "    result += B64URL[(n >> 12) & 63];\n")
  (fprintf port "    if (remaining >= 2) result += B64URL[(n >> 6) & 63];\n")
  (fprintf port "    if (remaining >= 3) result += B64URL[n & 63];\n")
  (fprintf port "  }\n")
  (fprintf port "  return result;\n")
  (fprintf port "}\n\n")
  ;; decode
  (fprintf port "export function base64urlDecode(str: string): Uint8Array {\n")
  (fprintf port "  const bytes: number[] = [];\n")
  (fprintf port "  for (let i = 0; i < str.length; i += 4) {\n")
  (fprintf port "    const remaining = str.length - i;\n")
  (fprintf port "    const v0 = B64URL.indexOf(str[i]);\n")
  (fprintf port "    const v1 = i + 1 < str.length ? B64URL.indexOf(str[i + 1]) : 0;\n")
  (fprintf port "    const v2 = i + 2 < str.length ? B64URL.indexOf(str[i + 2]) : 0;\n")
  (fprintf port "    const v3 = i + 3 < str.length ? B64URL.indexOf(str[i + 3]) : 0;\n")
  (fprintf port "    const n = (v0 << 18) | (v1 << 12) | (v2 << 6) | v3;\n")
  (fprintf port "    bytes.push((n >> 16) & 255);\n")
  (fprintf port "    if (remaining >= 3) bytes.push((n >> 8) & 255);\n")
  (fprintf port "    if (remaining >= 4) bytes.push(n & 255);\n")
  (fprintf port "  }\n")
  (fprintf port "  return new Uint8Array(bytes);\n")
  (fprintf port "}\n\n"))

;; --- Forward Transforms ---

(define (emit-forward-transforms port)
  (fprintf port "// --- Forward transforms (raw → encoded) ---\n\n")
  ;; TFromR
  (fprintf port "export function TFromR(code: string, raw: Uint8Array): string {\n")
  (fprintf port "  const ps = padSize(code, raw.length);\n")
  (fprintf port "  const padded = new Uint8Array(ps + raw.length);\n")
  (fprintf port "  padded.set(raw, ps);\n")
  (fprintf port "  const encoded = base64urlEncode(padded);\n")
  (fprintf port "  return code + encoded.slice(code.length);\n")
  (fprintf port "}\n\n")
  ;; BFromR
  (fprintf port "export function BFromR(code: string, raw: Uint8Array): Uint8Array {\n")
  (fprintf port "  return base64urlDecode(TFromR(code, raw));\n")
  (fprintf port "}\n\n"))

;; --- Reverse Transforms ---

(define (emit-reverse-transforms port)
  (fprintf port "// --- Reverse transforms (encoded → raw) ---\n\n")
  ;; RFromT
  (fprintf port "export function RFromT(text: string): ParseResult {\n")
  (fprintf port "  const cs = selectorDispatch(text[0]);\n")
  (fprintf port "  const code = text.slice(0, cs);\n")
  (fprintf port "  const entry = CODE_LOOKUP.get(code);\n")
  (fprintf port "  if (!entry) throw new Error(`Unknown CESR code: ${code}`);\n")
  (fprintf port "  const ps = padSize(code, entry.rawSize);\n")
  (fprintf port "  const restored = 'A'.repeat(cs) + text.slice(cs);\n")
  (fprintf port "  const padded = base64urlDecode(restored);\n")
  (fprintf port "  const raw = padded.slice(ps);\n")
  (fprintf port "  return { code, raw };\n")
  (fprintf port "}\n\n")
  ;; RFromB
  (fprintf port "export function RFromB(binary: Uint8Array): ParseResult {\n")
  (fprintf port "  return RFromT(base64urlEncode(binary));\n")
  (fprintf port "}\n"))

;; ============================================================
;; cesr-codec.test.ts emission
;; ============================================================

(define (emit-library-tests port)
  (fprintf port "// Auto-generated by CESR spec oracle — do not edit\n")
  (fprintf port "import { describe, test, expect } from 'vitest';\n")
  (fprintf port "import {\n")
  (fprintf port "  CODE_TABLE,\n")
  (fprintf port "  padSize,\n")
  (fprintf port "  leadConstrainedBits,\n")
  (fprintf port "  base64urlEncode, base64urlDecode,\n")
  (fprintf port "  TFromR, BFromR, RFromT, RFromB,\n")
  (fprintf port "  type CodeEntry,\n")
  (fprintf port "} from './cesr-codec';\n\n")
  ;; validRawForEntry helper
  (fprintf port "function validRawForEntry(entry: CodeEntry, fillByte: number): Uint8Array {\n")
  (fprintf port "  const raw = new Uint8Array(entry.rawSize).fill(fillByte);\n")
  (fprintf port "  const lcb = leadConstrainedBits(entry.code, entry.rawSize);\n")
  (fprintf port "  if (lcb > 0) {\n")
  (fprintf port "    const fullBytes = Math.floor(lcb / 8);\n")
  (fprintf port "    const remainingBits = lcb % 8;\n")
  (fprintf port "    for (let i = 0; i < fullBytes; i++) raw[i] = 0;\n")
  (fprintf port "    if (remainingBits > 0) {\n")
  (fprintf port "      raw[fullBytes] &= (1 << (8 - remainingBits)) - 1;\n")
  (fprintf port "    }\n")
  (fprintf port "  }\n")
  (fprintf port "  return raw;\n")
  (fprintf port "}\n\n")
  ;; test suite
  (fprintf port "describe('CESR Codec Library', () => {\n\n")
  ;; text round-trip
  (fprintf port "  test('text round-trip: encode then parse recovers code and raw', () => {\n")
  (fprintf port "    for (const entry of CODE_TABLE) {\n")
  (fprintf port "      const raw = validRawForEntry(entry, 42);\n")
  (fprintf port "      const text = TFromR(entry.code, raw);\n")
  (fprintf port "      const result = RFromT(text);\n")
  (fprintf port "      expect(result.code).toBe(entry.code);\n")
  (fprintf port "      expect(result.raw).toEqual(raw);\n")
  (fprintf port "    }\n")
  (fprintf port "  });\n\n")
  ;; binary round-trip
  (fprintf port "  test('binary round-trip: encode then parse recovers code and raw', () => {\n")
  (fprintf port "    for (const entry of CODE_TABLE) {\n")
  (fprintf port "      const raw = validRawForEntry(entry, 42);\n")
  (fprintf port "      const bin = BFromR(entry.code, raw);\n")
  (fprintf port "      const result = RFromB(bin);\n")
  (fprintf port "      expect(result.code).toBe(entry.code);\n")
  (fprintf port "      expect(result.raw).toEqual(raw);\n")
  (fprintf port "    }\n")
  (fprintf port "  });\n\n")
  ;; code extraction
  (fprintf port "  test('code extraction: code is always recoverable', () => {\n")
  (fprintf port "    for (const entry of CODE_TABLE) {\n")
  (fprintf port "      const raw = new Uint8Array(entry.rawSize).fill(255);\n")
  (fprintf port "      const text = TFromR(entry.code, raw);\n")
  (fprintf port "      const result = RFromT(text);\n")
  (fprintf port "      expect(result.code).toBe(entry.code);\n")
  (fprintf port "    }\n")
  (fprintf port "  });\n\n")
  ;; parse equivalence
  (fprintf port "  test('parse equivalence: text and binary parse produce same raw', () => {\n")
  (fprintf port "    for (const entry of CODE_TABLE) {\n")
  (fprintf port "      const raw = validRawForEntry(entry, 42);\n")
  (fprintf port "      const text = TFromR(entry.code, raw);\n")
  (fprintf port "      const resultT = RFromT(text);\n")
  (fprintf port "      const resultB = RFromB(base64urlDecode(text));\n")
  (fprintf port "      expect(resultT.raw).toEqual(resultB.raw);\n")
  (fprintf port "    }\n")
  (fprintf port "  });\n")
  (fprintf port "});\n"))

;; ============================================================
;; Main
;; ============================================================

(define (emit-library output-dir)
  (make-directory* output-dir)
  ;; Write cesr-codec.ts
  (let ([lib-path (build-path output-dir "cesr-codec.ts")])
    (call-with-output-file lib-path
      (lambda (port)
        (emit-header port)
        (emit-types port)
        (emit-tables port)
        (emit-lookup-map port)
        (emit-sizing-fns port)
        (emit-selector-dispatch port)
        (emit-lead-constrained-bits port)
        (emit-base64url port)
        (emit-forward-transforms port)
        (emit-reverse-transforms port))
      #:exists 'replace)
    (printf "Wrote ~a\n" lib-path))
  ;; Write cesr-codec.test.ts
  (let ([test-path (build-path output-dir "cesr-codec.test.ts")])
    (call-with-output-file test-path
      (lambda (port)
        (emit-library-tests port))
      #:exists 'replace)
    (printf "Wrote ~a\n" test-path)))

(module+ main
  (let* ([args (current-command-line-arguments)]
         [output-dir (if (> (vector-length args) 0)
                         (vector-ref args 0)
                         "../output")])
    (emit-library output-dir)))
