#lang racket/base

;; Emit TypeScript property-based tests from CESR algebraic laws.
;; Produces a self-contained vitest + fast-check file.
;; Usage: racket emit-property-tests.rkt <output-dir>

(require racket/file
         "../cesr/laws.rkt"
         "../cesr/tables.rkt"
         "../cesr/counters.rkt")

;; --- Helpers ---

(define (js-string s)
  (format "'~a'" s))

;; --- Header ---

(define (emit-header port)
  (fprintf port "// Auto-generated by CESR spec oracle — do not edit\n")
  (fprintf port "import { describe, test, expect } from 'vitest';\n")
  (fprintf port "import * as fc from 'fast-check';\n\n"))

;; --- Code table ---

(define (emit-code-table port)
  (fprintf port "// --- Code table (from oracle) ---\n")
  (fprintf port "const CODE_TABLE = [\n")
  (for ([entry (all-entries)])
    (fprintf port "  { code: ~a, description: ~a, rawSize: ~a, category: ~a },\n"
             (js-string (entry-code entry))
             (js-string (entry-description entry))
             (entry-raw-size entry)
             (js-string (entry-category entry))))
  (fprintf port "] as const;\n\n"))

;; --- Counter table ---

(define (emit-counter-table port)
  (fprintf port "// --- Counter table (from oracle) ---\n")
  (fprintf port "const COUNTER_TABLE = [\n")
  (for ([entry (all-counter-entries)])
    (fprintf port "  { code: ~a, description: ~a, countRange: ~a, category: ~a },\n"
             (js-string (counter-entry-code entry))
             (js-string (counter-entry-description entry))
             (counter-entry-count-range entry)
             (js-string (counter-entry-category entry))))
  (fprintf port "] as const;\n\n"))

;; --- Reference implementations ---

(define (emit-reference-impls port)
  (fprintf port "// --- Reference implementations (translated from cesr/math.rkt) ---\n\n")

  ;; padSize
  (fprintf port "function padSize(_code: string, rawSize: number): number {\n")
  (fprintf port "  const r = rawSize % 3;\n")
  (fprintf port "  return r === 0 ? 0 : 3 - r;\n")
  (fprintf port "}\n\n")

  ;; textSize
  (fprintf port "function textSize(code: string, rawSize: number): number {\n")
  (fprintf port "  const ps = padSize(code, rawSize);\n")
  (fprintf port "  return ((ps + rawSize) / 3) * 4;\n")
  (fprintf port "}\n\n")

  ;; binarySize
  (fprintf port "function binarySize(code: string, rawSize: number): number {\n")
  (fprintf port "  return padSize(code, rawSize) + rawSize;\n")
  (fprintf port "}\n\n")

  ;; counterTextSize
  (fprintf port "function counterTextSize(code: string): number {\n")
  (fprintf port "  return 2 * code.length;\n")
  (fprintf port "}\n\n")

  ;; counterBinarySize
  (fprintf port "function counterBinarySize(code: string): number {\n")
  (fprintf port "  return (3 * counterTextSize(code)) / 4;\n")
  (fprintf port "}\n\n")

  ;; base64url alphabet
  (fprintf port "const B64URL = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';\n\n")

  ;; base64urlEncode
  (fprintf port "function base64urlEncode(bytes: Uint8Array): string {\n")
  (fprintf port "  let result = '';\n")
  (fprintf port "  for (let i = 0; i < bytes.length; i += 3) {\n")
  (fprintf port "    const b0 = bytes[i];\n")
  (fprintf port "    const b1 = i + 1 < bytes.length ? bytes[i + 1] : 0;\n")
  (fprintf port "    const b2 = i + 2 < bytes.length ? bytes[i + 2] : 0;\n")
  (fprintf port "    const n = (b0 << 16) | (b1 << 8) | b2;\n")
  (fprintf port "    const remaining = bytes.length - i;\n")
  (fprintf port "    result += B64URL[(n >> 18) & 63];\n")
  (fprintf port "    result += B64URL[(n >> 12) & 63];\n")
  (fprintf port "    if (remaining >= 2) result += B64URL[(n >> 6) & 63];\n")
  (fprintf port "    if (remaining >= 3) result += B64URL[n & 63];\n")
  (fprintf port "  }\n")
  (fprintf port "  return result;\n")
  (fprintf port "}\n\n")

  ;; base64urlDecode
  (fprintf port "function base64urlDecode(str: string): Uint8Array {\n")
  (fprintf port "  const bytes: number[] = [];\n")
  (fprintf port "  for (let i = 0; i < str.length; i += 4) {\n")
  (fprintf port "    const remaining = str.length - i;\n")
  (fprintf port "    const v0 = B64URL.indexOf(str[i]);\n")
  (fprintf port "    const v1 = i + 1 < str.length ? B64URL.indexOf(str[i + 1]) : 0;\n")
  (fprintf port "    const v2 = i + 2 < str.length ? B64URL.indexOf(str[i + 2]) : 0;\n")
  (fprintf port "    const v3 = i + 3 < str.length ? B64URL.indexOf(str[i + 3]) : 0;\n")
  (fprintf port "    const n = (v0 << 18) | (v1 << 12) | (v2 << 6) | v3;\n")
  (fprintf port "    bytes.push((n >> 16) & 255);\n")
  (fprintf port "    if (remaining >= 3) bytes.push((n >> 8) & 255);\n")
  (fprintf port "    if (remaining >= 4) bytes.push(n & 255);\n")
  (fprintf port "  }\n")
  (fprintf port "  return new Uint8Array(bytes);\n")
  (fprintf port "}\n\n")

  ;; TFromR
  (fprintf port "function TFromR(code: string, raw: Uint8Array): string {\n")
  (fprintf port "  const ps = padSize(code, raw.length);\n")
  (fprintf port "  const padded = new Uint8Array(ps + raw.length);\n")
  (fprintf port "  padded.set(raw, ps);\n")
  (fprintf port "  const encoded = base64urlEncode(padded);\n")
  (fprintf port "  return code + encoded.slice(code.length);\n")
  (fprintf port "}\n\n")

  ;; BFromR
  (fprintf port "function BFromR(code: string, raw: Uint8Array): Uint8Array {\n")
  (fprintf port "  return base64urlDecode(TFromR(code, raw));\n")
  (fprintf port "}\n\n")

  ;; CODE_LOOKUP
  (fprintf port "const CODE_LOOKUP = new Map<string, typeof CODE_TABLE[number]>();\n")
  (fprintf port "for (const entry of CODE_TABLE) {\n")
  (fprintf port "  CODE_LOOKUP.set(entry.code, entry);\n")
  (fprintf port "}\n\n")

  ;; selectorDispatch
  (fprintf port "function selectorDispatch(firstChar: string): 1 | 2 {\n")
  (fprintf port "  return (firstChar === '0' || firstChar === '-') ? 2 : 1;\n")
  (fprintf port "}\n\n")

  ;; leadConstrainedBits
  (fprintf port "function leadConstrainedBits(code: string, rawSize: number): number {\n")
  (fprintf port "  const cs = code.length;\n")
  (fprintf port "  const ps = padSize(code, rawSize);\n")
  (fprintf port "  return cs > ps ? (cs - ps) * 6 : 0;\n")
  (fprintf port "}\n\n")

  ;; validRawForEntry
  (fprintf port "function validRawForEntry(entry: typeof CODE_TABLE[number], fillByte: number): Uint8Array {\n")
  (fprintf port "  const raw = new Uint8Array(entry.rawSize).fill(fillByte);\n")
  (fprintf port "  const lcb = leadConstrainedBits(entry.code, entry.rawSize);\n")
  (fprintf port "  if (lcb > 0) {\n")
  (fprintf port "    const fullBytes = Math.floor(lcb / 8);\n")
  (fprintf port "    const remainingBits = lcb % 8;\n")
  (fprintf port "    for (let i = 0; i < fullBytes; i++) raw[i] = 0;\n")
  (fprintf port "    if (remainingBits > 0) {\n")
  (fprintf port "      raw[fullBytes] &= (1 << (8 - remainingBits)) - 1;\n")
  (fprintf port "    }\n")
  (fprintf port "  }\n")
  (fprintf port "  return raw;\n")
  (fprintf port "}\n\n")

  ;; ParseResult
  (fprintf port "interface ParseResult {\n")
  (fprintf port "  code: string;\n")
  (fprintf port "  raw: Uint8Array;\n")
  (fprintf port "}\n\n")

  ;; RFromT
  (fprintf port "function RFromT(text: string): ParseResult {\n")
  (fprintf port "  const cs = selectorDispatch(text[0]);\n")
  (fprintf port "  const code = text.slice(0, cs);\n")
  (fprintf port "  const entry = CODE_LOOKUP.get(code);\n")
  (fprintf port "  if (!entry) throw new Error(`Unknown CESR code: ${code}`);\n")
  (fprintf port "  const ps = padSize(code, entry.rawSize);\n")
  (fprintf port "  const restored = 'A'.repeat(cs) + text.slice(cs);\n")
  (fprintf port "  const padded = base64urlDecode(restored);\n")
  (fprintf port "  const raw = padded.slice(ps);\n")
  (fprintf port "  return { code, raw };\n")
  (fprintf port "}\n\n")

  ;; RFromB
  (fprintf port "function RFromB(binary: Uint8Array): ParseResult {\n")
  (fprintf port "  return RFromT(base64urlEncode(binary));\n")
  (fprintf port "}\n\n"))

;; --- Test blocks ---

(define combinatorial-sample
  '(("A" 64) ("D" 32) ("0F" 64) ("0G" 64)))

(define (emit-law-test port l)
  (case (law-id l)
    ;; === Sizing (table-universal) ===
    [(triplet-alignment)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const ps = padSize(entry.code, entry.rawSize);\n")
     (fprintf port "      expect((ps + entry.rawSize) % 3).toBe(0);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(quad-alignment)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const ts = textSize(entry.code, entry.rawSize);\n")
     (fprintf port "      expect(ts % 4).toBe(0);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(binary-triplet)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const bs = binarySize(entry.code, entry.rawSize);\n")
     (fprintf port "      expect(bs % 3).toBe(0);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(size-ratio)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const ts = textSize(entry.code, entry.rawSize);\n")
     (fprintf port "      const bs = binarySize(entry.code, entry.rawSize);\n")
     (fprintf port "      expect(bs * 4).toBe(ts * 3);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(pad-bounded)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const ps = padSize(entry.code, entry.rawSize);\n")
     (fprintf port "      expect([0, 1, 2]).toContain(ps);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(binary-decomposition)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const ps = padSize(entry.code, entry.rawSize);\n")
     (fprintf port "      const bs = binarySize(entry.code, entry.rawSize);\n")
     (fprintf port "      expect(bs).toBe(ps + entry.rawSize);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    ;; === Encoding (byte-sequence) ===
    [(base64url-round-trip)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    fc.assert(fc.property(\n")
     (fprintf port "      fc.uint8Array({ minLength: 0, maxLength: 100 }),\n")
     (fprintf port "      (raw) => {\n")
     (fprintf port "        const encoded = base64urlEncode(raw);\n")
     (fprintf port "        const decoded = base64urlDecode(encoded);\n")
     (fprintf port "        expect(decoded).toEqual(raw);\n")
     (fprintf port "      }\n")
     (fprintf port "    ));\n")
     (fprintf port "  });\n")]
    [(no-padding-chars)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    fc.assert(fc.property(\n")
     (fprintf port "      fc.uint8Array({ minLength: 0, maxLength: 100 }),\n")
     (fprintf port "      (raw) => {\n")
     (fprintf port "        const encoded = base64urlEncode(raw);\n")
     (fprintf port "        expect(encoded).not.toContain('=');\n")
     (fprintf port "      }\n")
     (fprintf port "    ));\n")
     (fprintf port "  });\n")]
    ;; === Transform (table-universal) ===
    [(code-preservation)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const raw = new Uint8Array(entry.rawSize).fill(42);\n")
     (fprintf port "      const text = TFromR(entry.code, raw);\n")
     (fprintf port "      expect(text.startsWith(entry.code)).toBe(true);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(text-length-preservation)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const raw = new Uint8Array(entry.rawSize).fill(42);\n")
     (fprintf port "      const text = TFromR(entry.code, raw);\n")
     (fprintf port "      expect(text.length).toBe(textSize(entry.code, entry.rawSize));\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(binary-length-preservation)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const raw = new Uint8Array(entry.rawSize).fill(42);\n")
     (fprintf port "      const bin = BFromR(entry.code, raw);\n")
     (fprintf port "      expect(bin.length).toBe(binarySize(entry.code, entry.rawSize));\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(transform-composition)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const raw = new Uint8Array(entry.rawSize).fill(42);\n")
     (fprintf port "      const fromText = base64urlDecode(TFromR(entry.code, raw));\n")
     (fprintf port "      const fromBin = BFromR(entry.code, raw);\n")
     (fprintf port "      expect(fromText).toEqual(fromBin);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    ;; === Self-framing (structural) ===
    [(selector-dispatch)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const firstChar = entry.code[0];\n")
     (fprintf port "      const cs = entry.code.length;\n")
     (fprintf port "      if (firstChar === '0' || firstChar === '-') {\n")
     (fprintf port "        expect(cs).toBe(2);\n")
     (fprintf port "      } else {\n")
     (fprintf port "        expect(cs).toBe(1);\n")
     (fprintf port "      }\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(code-determines-size)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    const seen = new Map<string, number>();\n")
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const ts = textSize(entry.code, entry.rawSize);\n")
     (fprintf port "      const existing = seen.get(entry.code);\n")
     (fprintf port "      if (existing !== undefined) {\n")
     (fprintf port "        expect(ts).toBe(existing);\n")
     (fprintf port "      }\n")
     (fprintf port "      seen.set(entry.code, ts);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    ;; === Composition (combinatorial) ===
    [(stream-concatenation)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    const sample = [\n")
     (for ([pair combinatorial-sample])
       (fprintf port "      { code: ~a, rawSize: ~a },\n"
                (js-string (car pair)) (list-ref pair 1)))
     (fprintf port "    ];\n")
     (fprintf port "    for (const e1 of sample) {\n")
     (fprintf port "      for (const e2 of sample) {\n")
     (fprintf port "        const raw1 = new Uint8Array(e1.rawSize).fill(1);\n")
     (fprintf port "        const raw2 = new Uint8Array(e2.rawSize).fill(2);\n")
     (fprintf port "        const combined = TFromR(e1.code, raw1) + TFromR(e2.code, raw2);\n")
     (fprintf port "        const expected = textSize(e1.code, e1.rawSize) + textSize(e2.code, e2.rawSize);\n")
     (fprintf port "        expect(combined.length).toBe(expected);\n")
     (fprintf port "      }\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    ;; === Counter laws (counter-universal) ===
    [(counter-quad-alignment)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of COUNTER_TABLE) {\n")
     (fprintf port "      const ts = counterTextSize(entry.code);\n")
     (fprintf port "      expect(ts % 4).toBe(0);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(counter-binary-triplet)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of COUNTER_TABLE) {\n")
     (fprintf port "      const bs = counterBinarySize(entry.code);\n")
     (fprintf port "      expect(bs % 3).toBe(0);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(counter-size-ratio)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of COUNTER_TABLE) {\n")
     (fprintf port "      const ts = counterTextSize(entry.code);\n")
     (fprintf port "      const bs = counterBinarySize(entry.code);\n")
     (fprintf port "      expect(bs * 4).toBe(ts * 3);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    ;; === Counter structural ===
    [(counter-selector-dispatch)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of COUNTER_TABLE) {\n")
     (fprintf port "      expect(entry.code[0]).toBe('-');\n")
     (fprintf port "      expect(entry.code.length).toBe(2);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    ;; === Parse laws (table-universal) ===
    [(text-round-trip)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const raw = validRawForEntry(entry, 42);\n")
     (fprintf port "      const text = TFromR(entry.code, raw);\n")
     (fprintf port "      const result = RFromT(text);\n")
     (fprintf port "      expect(result.code).toBe(entry.code);\n")
     (fprintf port "      expect(result.raw).toEqual(raw);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(binary-round-trip)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const raw = validRawForEntry(entry, 42);\n")
     (fprintf port "      const bin = BFromR(entry.code, raw);\n")
     (fprintf port "      const result = RFromB(bin);\n")
     (fprintf port "      expect(result.code).toBe(entry.code);\n")
     (fprintf port "      expect(result.raw).toEqual(raw);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(code-extraction)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const raw = new Uint8Array(entry.rawSize).fill(255);\n")
     (fprintf port "      const text = TFromR(entry.code, raw);\n")
     (fprintf port "      const result = RFromT(text);\n")
     (fprintf port "      expect(result.code).toBe(entry.code);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [(parse-equivalence)
     (fprintf port "  test('~a: ~a', () => {\n" (law-id l) (law-name l))
     (fprintf port "    for (const entry of CODE_TABLE) {\n")
     (fprintf port "      const raw = validRawForEntry(entry, 42);\n")
     (fprintf port "      const text = TFromR(entry.code, raw);\n")
     (fprintf port "      const resultT = RFromT(text);\n")
     (fprintf port "      const resultB = RFromB(base64urlDecode(text));\n")
     (fprintf port "      expect(resultT.raw).toEqual(resultB.raw);\n")
     (fprintf port "    }\n")
     (fprintf port "  });\n")]
    [else (error 'emit-law-test "unknown law: ~a" (law-id l))]))

;; --- Main emission ---

(define (emit-property-tests output-dir)
  (make-directory* output-dir)
  (let ([output-path (build-path output-dir "cesr-laws.property.ts")])
    (call-with-output-file output-path
      (lambda (port)
        (emit-header port)
        (emit-code-table port)
        (emit-counter-table port)
        (emit-reference-impls port)
        (fprintf port "// --- ~a law tests ---\n" (length (all-laws)))
        (fprintf port "describe('CESR Algebraic Laws', () => {\n")
        (for ([l (all-laws)])
          (fprintf port "\n")
          (emit-law-test port l))
        (fprintf port "});\n"))
      #:exists 'replace)
    (printf "Wrote ~a tests to ~a\n" (length (all-laws)) output-path)))

(module+ main
  (let* ([args (current-command-line-arguments)]
         [output-dir (if (> (vector-length args) 0)
                         (vector-ref args 0)
                         "../output")])
    (emit-property-tests output-dir)))
