import type { ICryptoProvider } from "../../interfaces/ICryptoProvider.js";
import type { IEventDatabase } from "../../interfaces/IEventDatabase.js";
import type { IndexedSiger } from "../signature/verifySigs.js";
import { Kever } from "../state/Kever.js";
import {
  Ilk,
  INCEPTION_ILKS,
  ROTATION_ILKS,
  ESTABLISHMENT_ILKS,
} from "../../types/EventTypes.js";
import {
  KelError,
  OutOfOrderError,
  DuplicityError,
  SequenceError,
} from "../../types/errors.js";
import { isValidSupersede } from "../delegation/supersedingRules.js";
import type { KeyStateRecord } from "../../types/KeyStateRecord.js";

/** A cue notification generated by the Kevery. */
export interface Cue {
  kind: "receipt" | "notice" | "witness";
  prefix: string;
  sn: number;
  said: string;
}

/** Options for creating a Kevery. */
export interface KeveryOptions {
  db: IEventDatabase;
  crypto: ICryptoProvider;
  /** Promiscuous mode: accept all events regardless of local prefix. */
  lax?: boolean;
  /** Events from protected (local) source. */
  local?: boolean;
}

/**
 * Kevery — Key Event Processing Facility.
 *
 * Manages a collection of Kevers (one per known AID) and dispatches
 * incoming events through the 5-path processing algorithm.
 */
export class Kevery {
  readonly kevers = new Map<string, Kever>();
  readonly db: IEventDatabase;
  readonly crypto: ICryptoProvider;
  readonly cues: Cue[] = [];
  readonly lax: boolean;
  readonly local: boolean;

  constructor(opts: KeveryOptions) {
    this.db = opts.db;
    this.crypto = opts.crypto;
    this.lax = opts.lax ?? true;
    this.local = opts.local ?? false;
  }

  /**
   * Process a serialized event with its signatures.
   *
   * Implements the 5-path dispatch algorithm (spec Section 8.3).
   *
   * @param raw - Serialized event bytes
   * @param fields - Parsed event fields
   * @param sigers - Controller indexed signatures
   * @returns Updated KeyStateRecord for the AID
   */
  async processEvent(
    raw: Uint8Array,
    fields: Record<string, unknown>,
    sigers: IndexedSiger[] = [],
  ): Promise<KeyStateRecord> {
    const prefix = fields.i as string;
    const ilk = fields.t as string;
    const sn = parseInt(fields.s as string, 16);
    const said = fields.d as string;

    // PATH 1: First inception (prefix NOT in kevers)
    if (!this.kevers.has(prefix)) {
      if (!INCEPTION_ILKS.has(ilk as Ilk)) {
        throw new OutOfOrderError(
          `No inception found for "${prefix}", cannot process ${ilk}`,
          prefix,
          sn,
        );
      }
      return this.processInception(raw, fields, sigers, prefix, said);
    }

    // PATH 2+: Subsequent events (prefix already in kevers)
    const kever = this.kevers.get(prefix)!;

    if (sn === 0) {
      // Duplicate inception
      return this.processDuplicateInception(kever, fields, sigers, said);
    }

    const expectedSn = kever.sn + 1;

    if (sn > expectedSn) {
      // Out of order
      throw new OutOfOrderError(
        `Out of order: expected sn <= ${expectedSn}, got ${sn}`,
        prefix,
        sn,
      );
    }

    if (sn === expectedSn) {
      // Normal next event
      return this.processInOrder(raw, fields, sigers, kever, sn, said);
    }

    // sn <= kever.sn — check for recovery or duplicity
    if (ROTATION_ILKS.has(ilk as Ilk) && isValidSupersede(ilk, sn, kever.sn, kever.lastEst.s)) {
      // Valid recovery rotation
      return this.processRecovery(raw, fields, sigers, kever, sn, said);
    }

    // Check if same event (idempotent) or duplicitous
    const existingSaids = await this.db.getKelEntry(prefix, sn);
    if (existingSaids.includes(said)) {
      // Same event — accept additional signatures (idempotent)
      await this.logSigs(prefix, said, sigers);
      return kever.toKeyStateRecord();
    }

    // Different SAID at same sn — likely duplicitous
    throw new DuplicityError(
      `Duplicitous event at sn ${sn} for "${prefix}"`,
      prefix,
      sn,
    );
  }

  private async processInception(
    raw: Uint8Array,
    fields: Record<string, unknown>,
    sigers: IndexedSiger[],
    prefix: string,
    said: string,
  ): Promise<KeyStateRecord> {
    const kever = new Kever();
    kever.incept(fields);
    this.kevers.set(prefix, kever);

    // Log event
    await this.logEvent(raw, prefix, 0, said, sigers);

    // Assign first-seen ordinal
    const fn = await this.db.appendFel(prefix, said);
    kever.fn = fn;
    await this.db.putFn(prefix, said, fn);
    await this.db.putDatetime(prefix, said, new Date().toISOString());

    // Store key state
    const ksr = kever.toKeyStateRecord();
    await this.db.putState(prefix, ksr);

    // Generate cue
    this.cues.push({ kind: "receipt", prefix, sn: 0, said });

    return ksr;
  }

  private async processDuplicateInception(
    kever: Kever,
    fields: Record<string, unknown>,
    sigers: IndexedSiger[],
    said: string,
  ): Promise<KeyStateRecord> {
    if (said === kever.lastEst.d && kever.sn === 0) {
      // Same inception — accept additional signatures
      await this.logSigs(kever.prefix, said, sigers);
      return kever.toKeyStateRecord();
    }
    // Different inception — duplicitous
    throw new DuplicityError(
      `Duplicitous inception for "${kever.prefix}"`,
      kever.prefix,
      0,
    );
  }

  private async processInOrder(
    raw: Uint8Array,
    fields: Record<string, unknown>,
    sigers: IndexedSiger[],
    kever: Kever,
    sn: number,
    said: string,
  ): Promise<KeyStateRecord> {
    kever.update(fields);

    // Log event
    await this.logEvent(raw, kever.prefix, sn, said, sigers);

    // Assign first-seen ordinal
    const fn = await this.db.appendFel(kever.prefix, said);
    kever.fn = fn;
    await this.db.putFn(kever.prefix, said, fn);
    await this.db.putDatetime(kever.prefix, said, new Date().toISOString());

    // Store key state
    const ksr = kever.toKeyStateRecord();
    await this.db.putState(kever.prefix, ksr);

    // Generate cue
    this.cues.push({ kind: "receipt", prefix: kever.prefix, sn, said });

    return ksr;
  }

  private async processRecovery(
    raw: Uint8Array,
    fields: Record<string, unknown>,
    sigers: IndexedSiger[],
    kever: Kever,
    sn: number,
    said: string,
  ): Promise<KeyStateRecord> {
    kever.update(fields);

    // Log event (add alongside existing entries at this sn)
    await this.logEvent(raw, kever.prefix, sn, said, sigers);

    // Assign first-seen ordinal
    const fn = await this.db.appendFel(kever.prefix, said);
    kever.fn = fn;
    await this.db.putFn(kever.prefix, said, fn);
    await this.db.putDatetime(kever.prefix, said, new Date().toISOString());

    // Store updated key state
    const ksr = kever.toKeyStateRecord();
    await this.db.putState(kever.prefix, ksr);

    this.cues.push({ kind: "receipt", prefix: kever.prefix, sn, said });

    return ksr;
  }

  private async logEvent(
    raw: Uint8Array,
    prefix: string,
    sn: number,
    said: string,
    sigers: IndexedSiger[],
  ): Promise<void> {
    await this.db.putEvent(prefix, said, raw);
    await this.db.addKelEntry(prefix, sn, said);
    if (sigers.length > 0) {
      await this.db.putSigs(prefix, said, sigers);
    }
  }

  private async logSigs(
    prefix: string,
    said: string,
    sigers: IndexedSiger[],
  ): Promise<void> {
    if (sigers.length > 0) {
      await this.db.putSigs(prefix, said, sigers);
    }
  }
}
