// Auto-generated by CESR spec oracle — do not edit

// --- Types ---

export interface CodeEntry {
  readonly code: string;
  readonly description: string;
  readonly rawSize: number;
  readonly category: string;
}

export interface CounterEntry {
  readonly code: string;
  readonly description: string;
  readonly countRange: number;
  readonly category: string;
}

export interface ParseResult {
  readonly code: string;
  readonly raw: Uint8Array;
}

// --- Tables ---

export const CODE_TABLE: readonly CodeEntry[] = [
  { code: 'A', description: 'Ed25519 indexed signature both same', rawSize: 64, category: 'indexed-signature' },
  { code: 'B', description: 'Ed25519 indexed signature current only', rawSize: 64, category: 'indexed-signature' },
  { code: 'C', description: 'Ed25519 indexed signature big both same', rawSize: 64, category: 'indexed-signature' },
  { code: 'D', description: 'Ed25519 verification key', rawSize: 32, category: 'verification-key' },
  { code: 'E', description: 'Blake3-256 digest', rawSize: 32, category: 'digest' },
  { code: 'F', description: 'Blake2b-256 digest', rawSize: 32, category: 'digest' },
  { code: 'G', description: 'Blake2s-256 digest', rawSize: 32, category: 'digest' },
  { code: 'H', description: 'SHA3-256 digest', rawSize: 32, category: 'digest' },
  { code: 'I', description: 'SHA2-256 digest', rawSize: 32, category: 'digest' },
  { code: 'J', description: 'Seed of Ed25519 private key', rawSize: 32, category: 'seed' },
  { code: 'K', description: 'Ed448 verification key', rawSize: 57, category: 'verification-key' },
  { code: 'L', description: 'X25519 public encryption key', rawSize: 32, category: 'encryption-key' },
  { code: '0A', description: 'Random salt 128 bit', rawSize: 16, category: 'salt' },
  { code: '0B', description: 'Ed25519 signature', rawSize: 64, category: 'signature' },
  { code: '0C', description: 'X25519 cipher text', rawSize: 24, category: 'cipher' },
  { code: '0D', description: 'Blake3-512 digest', rawSize: 64, category: 'digest' },
  { code: '0E', description: 'SHA3-512 digest', rawSize: 64, category: 'digest' },
  { code: '0F', description: 'Blake2b-512 digest', rawSize: 64, category: 'digest' },
  { code: '0G', description: 'SHA2-512 digest', rawSize: 64, category: 'digest' },
];

export const COUNTER_TABLE: readonly CounterEntry[] = [
  { code: '-A', description: 'Controller indexed signatures count', countRange: 4095, category: 'counter' },
  { code: '-B', description: 'Witness indexed signatures count', countRange: 4095, category: 'counter' },
];

// --- Lookup ---

export const CODE_LOOKUP: ReadonlyMap<string, CodeEntry> = new Map<string, CodeEntry>(
  CODE_TABLE.map(e => [e.code, e] as const)
);

// --- Sizing ---

export function padSize(_code: string, rawSize: number): number {
  const r = rawSize % 3;
  return r === 0 ? 0 : 3 - r;
}

export function textSize(code: string, rawSize: number): number {
  const ps = padSize(code, rawSize);
  return ((ps + rawSize) / 3) * 4;
}

export function binarySize(code: string, rawSize: number): number {
  return padSize(code, rawSize) + rawSize;
}

export function counterTextSize(code: string): number {
  return 2 * code.length;
}

export function counterBinarySize(code: string): number {
  return (3 * counterTextSize(code)) / 4;
}

export function selectorDispatch(firstChar: string): 1 | 2 {
  return (firstChar === '0' || firstChar === '-') ? 2 : 1;
}

export function leadConstrainedBits(code: string, rawSize: number): number {
  const cs = code.length;
  const ps = padSize(code, rawSize);
  return cs > ps ? (cs - ps) * 6 : 0;
}

// --- Base64url codec ---

const B64URL = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';

export function base64urlEncode(bytes: Uint8Array): string {
  let result = '';
  for (let i = 0; i < bytes.length; i += 3) {
    const b0 = bytes[i];
    const b1 = i + 1 < bytes.length ? bytes[i + 1] : 0;
    const b2 = i + 2 < bytes.length ? bytes[i + 2] : 0;
    const n = (b0 << 16) | (b1 << 8) | b2;
    const remaining = bytes.length - i;
    result += B64URL[(n >> 18) & 63];
    result += B64URL[(n >> 12) & 63];
    if (remaining >= 2) result += B64URL[(n >> 6) & 63];
    if (remaining >= 3) result += B64URL[n & 63];
  }
  return result;
}

export function base64urlDecode(str: string): Uint8Array {
  const bytes: number[] = [];
  for (let i = 0; i < str.length; i += 4) {
    const remaining = str.length - i;
    const v0 = B64URL.indexOf(str[i]);
    const v1 = i + 1 < str.length ? B64URL.indexOf(str[i + 1]) : 0;
    const v2 = i + 2 < str.length ? B64URL.indexOf(str[i + 2]) : 0;
    const v3 = i + 3 < str.length ? B64URL.indexOf(str[i + 3]) : 0;
    const n = (v0 << 18) | (v1 << 12) | (v2 << 6) | v3;
    bytes.push((n >> 16) & 255);
    if (remaining >= 3) bytes.push((n >> 8) & 255);
    if (remaining >= 4) bytes.push(n & 255);
  }
  return new Uint8Array(bytes);
}

// --- Forward transforms (raw → encoded) ---

export function TFromR(code: string, raw: Uint8Array): string {
  const ps = padSize(code, raw.length);
  const padded = new Uint8Array(ps + raw.length);
  padded.set(raw, ps);
  const encoded = base64urlEncode(padded);
  return code + encoded.slice(code.length);
}

export function BFromR(code: string, raw: Uint8Array): Uint8Array {
  return base64urlDecode(TFromR(code, raw));
}

// --- Reverse transforms (encoded → raw) ---

export function RFromT(text: string): ParseResult {
  const cs = selectorDispatch(text[0]);
  const code = text.slice(0, cs);
  const entry = CODE_LOOKUP.get(code);
  if (!entry) throw new Error(`Unknown CESR code: ${code}`);
  const ps = padSize(code, entry.rawSize);
  const restored = 'A'.repeat(cs) + text.slice(cs);
  const padded = base64urlDecode(restored);
  const raw = padded.slice(ps);
  return { code, raw };
}

export function RFromB(binary: Uint8Array): ParseResult {
  return RFromT(base64urlEncode(binary));
}
